name: Build

on:
  push:
    tags:

jobs:
  build_and_package:
    runs-on: ubuntu-latest
    container: rust:1.87
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache Cargo directories
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          target/ # Cache build target directory
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }} # Cache key
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Build Rust binary
      run: cargo build --release --target x86_64-unknown-linux-gnu

    - name: Release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        files: |
          target/release/hars-imp

